/* ================================================================
   APP.JS — Instantly loads 100 posts from ALL_POSTS (posts-data.js)
   Categories: JavaScript, Playwright, MCP
   ================================================================ */

const STORAGE_KEY = "jsPlaywrightMcpBlogPosts";
const CONTENT_VERSION = 5;

const form = document.getElementById("post-form");
const postIdInput = document.getElementById("post-id");
const titleInput = document.getElementById("title");
const categoryInput = document.getElementById("category");
const tagsInput = document.getElementById("tags");
const excerptInput = document.getElementById("excerpt");
const contentInput = document.getElementById("content");
const coverImageInput = document.getElementById("cover-image");
const coverPreview = document.getElementById("cover-preview");
const clearBtn = document.getElementById("clear-btn");
const postsContainer = document.getElementById("posts");
const searchInput = document.getElementById("search");
const filterCategory = document.getElementById("filter-category");
const exportBtn = document.getElementById("export-btn");
const importBtn = document.getElementById("import-btn");
const importFile = document.getElementById("import-file");
const template = document.getElementById("post-card-template");
const viewer = document.getElementById("viewer");
const viewerContent = document.getElementById("viewer-content");
let currentCoverImageData = "";

/* ── Helpers ────────────────────────────────────────────── */

function uid() {
  return `${Date.now()}-${Math.floor(Math.random() * 100000)}`;
}

function loadPosts() {
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function savePosts(posts) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(posts));
}

function formatDate(iso) {
  return new Date(iso).toLocaleString();
}

/* ── Load all 100 posts instantly ──────────────────────── */

function loadAllPostsFromNotes() {
  const existing = loadPosts();

  // Check if already loaded at current version
  if (existing.length > 0 && existing[0] && existing[0].contentVersion === CONTENT_VERSION) {
    return; // Already loaded
  }

  // Clear old posts and regenerate from ALL_POSTS
  const now = Date.now();
  const posts = ALL_POSTS.map((src, i) => ({
    id: `note-${src.id}-${now}`,
    title: src.title,
    category: src.category,
    tags: src.tags,
    excerpt: src.excerpt,
    coverImageData: "",
    content: src.content,
    sourceUrl: "",
    createdAt: new Date(now - i * 60000).toISOString(),
    autoGenerated: true,
    contentVersion: CONTENT_VERSION,
  }));

  savePosts(posts);
}

/* ── Filter & Search ───────────────────────────────────── */

function currentFilters() {
  return {
    search: searchInput.value.trim().toLowerCase(),
    category: filterCategory.value,
  };
}

function filteredPosts(posts) {
  const { search, category } = currentFilters();
  return posts
    .filter((post) => {
      const categoryMatch = category === "All" || post.category === category;
      const searchMatch =
        search.length === 0 ||
        post.title.toLowerCase().includes(search) ||
        post.excerpt.toLowerCase().includes(search) ||
        post.content.toLowerCase().includes(search) ||
        post.tags.join(" ").toLowerCase().includes(search);
      return categoryMatch && searchMatch;
    })
    .sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
}

/* ── Markdown to HTML Renderer ─────────────────────────── */

function escapeHtml(text) {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function markdownToHtml(markdown) {
  const escaped = escapeHtml(markdown || "");

  // Fenced code blocks
  const fenced = escaped.replace(/```(\w*)\n?([\s\S]*?)```/g, (_m, lang, code) => {
    const cls = lang ? ` class="lang-${lang}"` : "";
    return `<pre><code${cls}>${code.trim()}</code></pre>`;
  });

  // Headings
  const headings = fenced
    .replace(/^###\s+(.*)$/gm, "<h3>$1</h3>")
    .replace(/^##\s+(.*)$/gm, "<h2>$1</h2>")
    .replace(/^#\s+(.*)$/gm, "<h1>$1</h1>");

  // Inline formatting
  const bold = headings.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  const italic = bold.replace(/\*(.+?)\*/g, "<em>$1</em>");
  const inlineCode = italic.replace(/`([^`]+)`/g, "<code>$1</code>");

  // Links
  const links = inlineCode.replace(
    /\[(.+?)\]\((https?:\/\/[^\s)]+)\)/g,
    '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>'
  );

  // Tables (simple pipe tables)
  const withTables = links.replace(
    /(?:^|\n)(\|.+\|)\n(\|[-| :]+\|)\n((?:\|.+\|\n?)+)/g,
    (_m, headerRow, _sep, bodyRows) => {
      const headers = headerRow.split("|").filter(Boolean).map(h => `<th>${h.trim()}</th>`).join("");
      const rows = bodyRows.trim().split("\n").map(row => {
        const cells = row.split("|").filter(Boolean).map(c => `<td>${c.trim()}</td>`).join("");
        return `<tr>${cells}</tr>`;
      }).join("");
      return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
    }
  );

  // Lists
  const withLists = withTables.replace(/(?:^|\n)(-\s+.+(?:\n-\s+.+)*)/g, (chunk) => {
    const items = chunk
      .trim()
      .split("\n")
      .map((line) => line.replace(/^-\s+/, "").trim())
      .filter(Boolean)
      .map((item) => `<li>${item}</li>`)
      .join("");
    return `<ul>${items}</ul>`;
  });

  // Blockquotes
  const withQuotes = withLists.replace(/(?:^|\n)&gt;\s+(.+)/g, '<blockquote>$1</blockquote>');

  return withQuotes
    .split(/\n\n+/)
    .map((block) => {
      const trimmed = block.trim();
      if (!trimmed) return "";
      if (/^<h[1-3]>|^<ul>|^<pre>|^<table>|^<blockquote>/.test(trimmed)) return trimmed;
      return `<p>${trimmed.replace(/\n/g, "<br>")}</p>`;
    })
    .join("\n");
}

/* ── Post Viewer ───────────────────────────────────────── */

function viewPost(post) {
  viewerContent.innerHTML = `
    <div class="viewer-header">
      <span class="category cat-${post.category.toLowerCase()}">${escapeHtml(post.category)}</span>
      <time>${escapeHtml(formatDate(post.createdAt))}</time>
    </div>
    <h2>${escapeHtml(post.title)}</h2>
    <p class="viewer-excerpt">${escapeHtml(post.excerpt)}</p>
    <div class="viewer-tags">${post.tags.map((t) => `<span class="tag">#${escapeHtml(t)}</span>`).join(" ")}</div>
    <div class="post-body">${markdownToHtml(post.content)}</div>
  `;
  viewer.showModal();
}

/* ── Rendering ─────────────────────────────────────────── */

function renderEmpty() {
  postsContainer.innerHTML =
    '<p class="empty-state">No posts match this filter. Try another category or search term.</p>';
}

function renderPosts() {
  const posts = filteredPosts(loadPosts());
  postsContainer.innerHTML = "";

  if (posts.length === 0) {
    renderEmpty();
    return;
  }

  // Show count
  const countEl = document.createElement("p");
  countEl.className = "post-count";
  countEl.textContent = `Showing ${posts.length} post${posts.length !== 1 ? "s" : ""}`;
  postsContainer.appendChild(countEl);

  posts.forEach((post, index) => {
    const fragment = template.content.cloneNode(true);
    const card = fragment.querySelector(".post-card");
    const cardCover = fragment.querySelector(".card-cover");

    card.style.animationDelay = `${Math.min(index * 20, 200)}ms`;
    if (post.coverImageData) {
      cardCover.src = post.coverImageData;
      cardCover.classList.remove("hidden");
    }
    const catSpan = fragment.querySelector(".category");
    catSpan.textContent = post.category;
    catSpan.className = `category cat-${post.category.toLowerCase()}`;

    fragment.querySelector("time").textContent = formatDate(post.createdAt);
    fragment.querySelector("h3").textContent = post.title;
    fragment.querySelector(".excerpt").textContent = post.excerpt;

    const tags = fragment.querySelector(".tags");
    post.tags.forEach((tag) => {
      const span = document.createElement("span");
      span.className = "tag";
      span.textContent = `#${tag}`;
      tags.appendChild(span);
    });

    fragment.querySelector(".read-btn").addEventListener("click", () => viewPost(post));
    fragment.querySelector(".edit-btn").addEventListener("click", () => editPost(post));
    fragment.querySelector(".delete-btn").addEventListener("click", () => deletePost(post.id));

    postsContainer.appendChild(fragment);
  });
}

/* ── Form: Create / Edit / Delete ──────────────────────── */

function resetForm() {
  postIdInput.value = "";
  currentCoverImageData = "";
  coverPreview.src = "";
  coverPreview.classList.add("hidden");
  form.reset();
}

function editPost(post) {
  postIdInput.value = post.id;
  titleInput.value = post.title;
  categoryInput.value = post.category;
  tagsInput.value = post.tags.join(", ");
  excerptInput.value = post.excerpt;
  contentInput.value = post.content;
  currentCoverImageData = post.coverImageData || "";
  if (currentCoverImageData) {
    coverPreview.src = currentCoverImageData;
    coverPreview.classList.remove("hidden");
  } else {
    coverPreview.classList.add("hidden");
  }
  titleInput.focus();
}

function deletePost(id) {
  const posts = loadPosts().filter((p) => p.id !== id);
  savePosts(posts);
  renderPosts();
}

form.addEventListener("submit", (event) => {
  event.preventDefault();

  const post = {
    id: postIdInput.value || uid(),
    title: titleInput.value.trim(),
    category: categoryInput.value,
    tags: tagsInput.value
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean),
    excerpt: excerptInput.value.trim(),
    coverImageData: currentCoverImageData,
    content: contentInput.value.trim(),
    sourceUrl: "",
    createdAt: new Date().toISOString(),
    contentVersion: CONTENT_VERSION,
  };

  const posts = loadPosts();
  const existingIndex = posts.findIndex((p) => p.id === post.id);
  if (existingIndex >= 0) {
    post.createdAt = posts[existingIndex].createdAt;
    posts[existingIndex] = post;
  } else {
    posts.push(post);
  }

  savePosts(posts);
  resetForm();
  renderPosts();
});

/* ── Event Listeners ───────────────────────────────────── */

clearBtn.addEventListener("click", resetForm);
searchInput.addEventListener("input", renderPosts);
filterCategory.addEventListener("change", renderPosts);

coverImageInput.addEventListener("change", async () => {
  const file = coverImageInput.files?.[0];
  if (!file) {
    currentCoverImageData = "";
    coverPreview.classList.add("hidden");
    return;
  }
  const reader = new FileReader();
  reader.onload = () => {
    currentCoverImageData = String(reader.result || "");
    if (currentCoverImageData) {
      coverPreview.src = currentCoverImageData;
      coverPreview.classList.remove("hidden");
    }
  };
  reader.readAsDataURL(file);
});

exportBtn.addEventListener("click", () => {
  const posts = loadPosts();
  const blob = new Blob([JSON.stringify(posts, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `blog-posts-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
});

importBtn.addEventListener("click", () => importFile.click());

importFile.addEventListener("change", async () => {
  const file = importFile.files?.[0];
  if (!file) return;
  try {
    const text = await file.text();
    const parsed = JSON.parse(text);
    if (!Array.isArray(parsed)) throw new Error("Invalid JSON format");
    const cleaned = parsed
      .filter((p) => p && typeof p.title === "string" && typeof p.content === "string")
      .map((p) => ({
        id: p.id || uid(),
        title: String(p.title),
        category: ["JavaScript", "Playwright", "MCP", "TOSCA", "Both"].includes(p.category) ? p.category : "Both",
        tags: Array.isArray(p.tags) ? p.tags.map(String) : [],
        excerpt: String(p.excerpt || ""),
        coverImageData: String(p.coverImageData || ""),
        content: String(p.content),
        sourceUrl: String(p.sourceUrl || ""),
        createdAt: p.createdAt ? String(p.createdAt) : new Date().toISOString(),
        contentVersion: CONTENT_VERSION,
      }));
    savePosts(cleaned);
    renderPosts();
  } catch (error) {
    alert(`Import failed: ${error.message || error}`);
  } finally {
    importFile.value = "";
  }
});

/* ── Initialize: Load all 100 posts instantly ──────────── */
loadAllPostsFromNotes();
renderPosts();
